name: Reusable Build and Deploy for Spring boot application

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    name: Build the application
    uses: muskan04yadav/spring_build_workflow/.github/workflows/build.yml@main
    secrets:
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


  deploy:
    needs: build
    uses: muskan04yadav/spring_deploy_workflow/.github/workflows/deploy.yml@main
    with:
      image_name: ${{ inputs.image_name }}
      container_name: ${{ inputs.container_name }}
    secrets:
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
